### ISSUE TITLE
pytest-level plugins not suitable with pytest-sugar. 

### ISSUE THREAD

**Issue by k3v8ns** [encukou/pytest-level#1]
pytest-level plugins not suitable with pytest-sugar. 

```log
logs: 

Test session starts (platform: darwin, Python 3.7.3, pytest 4.5.0, pytest-sugar 0.9.2)
rootdir: /Users/selfs/Projects/pytest_level, inifile: pytest.ini
plugins: xdist-1.28.0, timeout-1.3.3, sugar-0.9.2, metadata-1.8.0, level-0.1.1, html-1.20.0, forked-1.0.2, dependency-0.4.0
timeout: 7200.0s
timeout method: signal
timeout func_only: False
collecting ... INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/_pytest/main.py", line 205, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/_pytest/main.py", line 248, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/_pytest/main.py", line 258, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/_pytest/main.py", line 497, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pytest_level.py", line 25, in pytest_collection_modifyitems
INTERNALERROR>     config.hook.pytest_deselected(items=deselected_items)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/selfs/miniconda2/envs/py37/lib/python3.7/site-packages/pytest_sugar.py", line 94, in pytest_deselected
INTERNALERROR>     pluginmanager = items[0].config.pluginmanager
INTERNALERROR> TypeError: 'set' object is not subscriptable


Results (15.32s):
       1 deselected
```

**Comment by encukou** [comment]
Feel free to contribute a fix!

**Comment by k3v8ns** [comment]
change set(items) to  list()  and  push code commit to fork repo. please check.
